name: Build project

on:
  workflow_call:
  workflow_dispatch:

jobs:
  builder:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker compose -f ./backend/docker-compose.yml build app

      - name: Build project
        run: |
          docker compose -f ./backend/docker-compose.yml run \
            cargo build

      - name: Build WASM
        run: |
          docker compose -f ./backend/docker-compose.yml run \
            wasm-pack build --target web
